//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumPoolTarget) DeepCopyInto(out *CiliumPoolTarget) {
	*out = *in
	if in.ServiceSelector != nil {
		in, out := &in.ServiceSelector, &out.ServiceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumPoolTarget.
func (in *CiliumPoolTarget) DeepCopy() *CiliumPoolTarget {
	if in == nil {
		return nil
	}
	out := new(CiliumPoolTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookCluster) DeepCopyInto(out *ClusterbookCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookCluster.
func (in *ClusterbookCluster) DeepCopy() *ClusterbookCluster {
	if in == nil {
		return nil
	}
	out := new(ClusterbookCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookClusterList) DeepCopyInto(out *ClusterbookClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterbookCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookClusterList.
func (in *ClusterbookClusterList) DeepCopy() *ClusterbookClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterbookClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookClusterSpec) DeepCopyInto(out *ClusterbookClusterSpec) {
	*out = *in
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.ExistingSecretRef != nil {
		in, out := &in.ExistingSecretRef, &out.ExistingSecretRef
		*out = new(SecretObjectRef)
		**out = **in
	}
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookClusterSpec.
func (in *ClusterbookClusterSpec) DeepCopy() *ClusterbookClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterbookClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookClusterStatus) DeepCopyInto(out *ClusterbookClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookClusterStatus.
func (in *ClusterbookClusterStatus) DeepCopy() *ClusterbookClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterbookClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookLoadBalancer) DeepCopyInto(out *ClusterbookLoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookLoadBalancer.
func (in *ClusterbookLoadBalancer) DeepCopy() *ClusterbookLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(ClusterbookLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookLoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookLoadBalancerList) DeepCopyInto(out *ClusterbookLoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterbookLoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookLoadBalancerList.
func (in *ClusterbookLoadBalancerList) DeepCopy() *ClusterbookLoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(ClusterbookLoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookLoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookLoadBalancerSpec) DeepCopyInto(out *ClusterbookLoadBalancerSpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.CiliumPool != nil {
		in, out := &in.CiliumPool, &out.CiliumPool
		*out = new(CiliumPoolTarget)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookLoadBalancerSpec.
func (in *ClusterbookLoadBalancerSpec) DeepCopy() *ClusterbookLoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterbookLoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookLoadBalancerStatus) DeepCopyInto(out *ClusterbookLoadBalancerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookLoadBalancerStatus.
func (in *ClusterbookLoadBalancerStatus) DeepCopy() *ClusterbookLoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterbookLoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookProviderConfig) DeepCopyInto(out *ClusterbookProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookProviderConfig.
func (in *ClusterbookProviderConfig) DeepCopy() *ClusterbookProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterbookProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookProviderConfigList) DeepCopyInto(out *ClusterbookProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterbookProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookProviderConfigList.
func (in *ClusterbookProviderConfigList) DeepCopy() *ClusterbookProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterbookProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterbookProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterbookProviderConfigSpec) DeepCopyInto(out *ClusterbookProviderConfigSpec) {
	*out = *in
	if in.CustomCASecretRef != nil {
		in, out := &in.CustomCASecretRef, &out.CustomCASecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterbookProviderConfigSpec.
func (in *ClusterbookProviderConfigSpec) DeepCopy() *ClusterbookProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterbookProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectRef) DeepCopyInto(out *SecretObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectRef.
func (in *SecretObjectRef) DeepCopy() *SecretObjectRef {
	if in == nil {
		return nil
	}
	out := new(SecretObjectRef)
	in.DeepCopyInto(out)
	return out
}
